name: Build

on:
  push:
    branches:
    - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' 

      - name: build
        run: go build main.go
